---
- name: install prerequisites
  sudo: true
  apt: pkg={{ item }}
  with_items:
    - automake
    - exuberant-ctags
    - git
    - libgmp3-dev
    - libncurses5-dev
    - libsigsegv-dev
    - libssl-dev
    - libtool
    - make
    - openssl

# - include: deb.yml
- include: git.yml
