---
- include: urbit.yml

- name: reinstall urbit on the vagrant box after a breach
  hosts: all
  gather_facts: false
  vars:
    urbit_git_install_path: /home/{{ ansible_ssh_user }}/urbit
  tasks:
    - name: force update the git repo
      git: repo=https://github.com/urbit/urbit.git
           dest={{ urbit_git_install_path }}
           depth=1
           update=true
           force=true

    - name: clean up old build artifacts
      command: make clean
               chdir={{ urbit_git_install_path }}

    - name: compile new version of urbit
      command: make debbuild
               chdir={{ urbit_git_install_path }}

    - name: ensure compiled artifact present
      file: path={{ urbit_git_install_path }}/.made

    - name: install new version of urbit
      sudo: true
      shell: make debinstall
             chdir={{ urbit_git_install_path }}

    - name: ensure installed artifact present
      file: path={{ urbit_git_install_path }}/.installed

- include: backup.yml

- name: remove pier
  hosts: all
  gather_facts: false
  tasks:
    - name: remove old pier directory
      file: path=/vagrant/mypier
            state=absent
