---
- name: update the aptitude cache
  become: yes
  become_method: sudo
  apt: cache_valid_time=3600
       update_cache=true

- name: install standard packages
  become: yes
  become_method: sudo
  apt: pkg={{ item }}
  with_items:
    - apt-transport-https
    - automake
    - build-essential
    - ca-certificates
    - cmake
    - curl
    - g++
    - git
    - libsigsegv-dev
    - libssl-dev
    - libtool
    - lsb-release
    - make
    - python
    - python-software-properties
    - screen
    - subversion
    - traceroute
    - vim
    - wget

- name: uninstall specific packages
  become: yes
  become_method: sudo
  apt: pkg={{ item }}
       state=absent
  with_items:
    - chef
    - chef-zero
    - puppet
    - puppet-common
